### ISSUE TITLE
`title_from_note_file': undefined method `gsub' for nil:NilClass (NoMethodError

### ISSUE THREAD

**Issue by brokosz** [bomberstudios/noteplan-backlinks#1]
Getting an error...

OS: Catalina
NotePlan: 2.4.3
ruby: 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

```
Traceback (most recent call last):
	3: from /Users/brokosz/bin/backlinks.rb:68:in `<main>'
	2: from /Users/brokosz/bin/backlinks.rb:68:in `each'
	1: from /Users/brokosz/bin/backlinks.rb:70:in `block in <main>'
/Users/brokosz/bin/backlinks.rb:20:in `title_from_note_file': undefined method `gsub' for nil:NilClass (NoMethodError)
```

**Comment by CalebSordelet** [comment]
This should solve your issue, it was returning a null object most likely because it didn't actually find any files, because it wasn't searching recursively, and yes, `example/**/*.{txt,md}` also looks in the example directory, not just subs ;-)

**Comment by brokosz** [comment]
Thanks, @CalebSordelet but I'm still getting the same error after the change from your PR.

**Comment by CalebSordelet** [comment]
Can you send a list of all files and directories in PATH_TO_NOTES, we can also collaborate over another medium if you prefer.

**Comment by CalebSordelet** [comment]
Also you NEED to make sure that there are no empty txt or md files, that would be what breaks your app, I can add a simple try catch for you that way even if some files fail the others will work.

**Comment by brokosz** [comment]
Thanks Caleb. But to be honest, the files are a little messy... imported mostly from nvAlt or Bear. I ran detox and did a TON of clean up, but still getting the same error. I think I need to add a catch for files that don't have a first line, to your point about empty files.

**Comment by brokosz** [comment]
Yup, empty first line was the issue. I think if @bomberstudios wants to support Calendar files in the future, error handling around empty files will be critical. Just clicking on a day in Calendar view creates an empty text file.

**Comment by bomberstudios** [comment]
Thank you so much for the report and the fix, @brokosz and @CalebSordelet. I definitely plan on adding some error handling to the script (this was a quick job to get me started).
