### ISSUE TITLE
Noteplan Beta 3

### ISSUE THREAD

**Issue by lightsquared** [bomberstudios/noteplan-backlinks#4]
Not sure if you are running the beta of Noteplan, but the ruby script does not work with the current path.  I think it changed because of iCloud Sync.  Anyway, my path to NotePlan Beta 3 is

/Library/Containers/co.noteplan.NotePlan3/Data/Library/Application Support/co.noteplan.NotePlan3

I updated line 4 in your ruby file with the new path and it worked fine.  I also changed the bullet type from "-" to "*".  The dash for me is a to-do.  Long story but is based on another application I use for academic editing of markdown (Zettlr).

Great little application.  I know the NotePlan developer is looking into backlinks.

**Comment by bomberstudios** [comment]
Hi there!

Thanks for the kind words. Since NotePlan 3 is out and already supports backlinks natively, I will not be updating the script to support it. I’m sure the people staying on NotePlan 2 will appreciate it if the script keeps working for them : )
